# HTTP Server.
server:
  address:             ":8199"
  dumpRouterMap:       true
  routeOverWrite:      true
  accessLogEnabled:    true
  openapiPath:         "/api.json"
  swaggerPath:         "/swagger"
  searchPaths:         "/static" 

# Socket Server
socket:
  address:                ":8187"

# Global logging.
logger:
    level : "all"
    stdout: true

# Database.
database:
  logger:
    level:   "all"
    stdout:  true

  default:
    link:   "mysql:root@tcp(127.0.0.1:3306)/gf_demo"
    debug:  true

